# Generated by Django 5.1.1 on 2024-12-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'permissions': [('view_history', 'can view history')]},
        ),
    ]
