# Generated by Django 5.1.1 on 2024-12-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
